[features]
seeds = false
skip-lint = false
[programs.localnet]
quora_solana = "9n8Y27TNBMzh83osNpmXX3accbQiUcHCQbvvunzzb5p9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/workspaces/solana-anchor-codespace/solana-local-config/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
